//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace SportsStore.Domain.Entities
{
	/// <summary>
	/// Database       : zartan24_mysqldb
	/// Data Source    : 192.168.1.4
	/// Server Version : 5.7.13-log
	/// </summary>
	public partial class zartan24_mysqldbDB : LinqToDB.Data.DataConnection
	{
		public ITable<product> products { get { return this.GetTable<product>(); } }

		public zartan24_mysqldbDB()
		{
			InitDataContext();
		}

		public zartan24_mysqldbDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("products")]
	public partial class product
	{
		[PrimaryKey, Identity   ] public int     ProductId     { get; set; } // int(4)
		[Column,     NotNull    ] public string  Name          { get; set; } // varchar(100)
		[Column,     NotNull    ] public string  Description   { get; set; } // varchar(500)
		[Column,     NotNull    ] public string  Category      { get; set; } // varchar(50)
		[Column,     NotNull    ] public decimal Price         { get; set; } // decimal(16,2)
		[Column,        Nullable] public byte[]  ImageData     { get; set; } // mediumblob
		[Column,        Nullable] public string  ImageMimeType { get; set; } // varchar(50)
	}

	public static partial class TableExtensions
	{
		public static product Find(this ITable<product> table, int ProductId)
		{
			return table.FirstOrDefault(t =>
				t.ProductId == ProductId);
		}
	}
}
